import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.8

[window.padding]
x = 20
y = 20

[env]
TERM = "xterm-256color"
